server:
  port: 8761

spring:
  application:
    name: SERVICE-A
  datasource:
    druid:

      # WebStatFilter 用于采集 web-jdbc 关联监控的数据。
      web-stat-filter:
        # 是否开启 WebStatFilter 默认是 true
        enabled: true
        # 需要拦截的 url
        url-pattern: /*
        # 排除静态资源的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      # Druid 内置提供了一个 StatViewServlet 用于展示 Druid 的统计信息。
      stat-view-servlet:
        #是否启用 StatViewServlet 默认值 true
        enabled: true
        # 需要拦截的 url
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: druid
        login-password: druid
nacos:
  config:
    #nacos地址
    server-addr: 134.175.217.13:8848
    #命名空间
    namespace: 459cd446-2e99-47d6-a516-9c6952c0aa1d
    #配置文件类型，目前只支持yaml,yml,properties,目前不需要了
    file-extension: yaml
    #默认提供者，目前不需要了
    prefix: SERVICE-A
rocketmq:
  # 生产者配置
  producer:
    #该应用是否启用生产者
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    groupName: mygroup
    # 服务地址
    namesrvAddr: 129.211.71.185:9876
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
  # 消费者配置
  consumer:
    #该应用是否启用消费者
    isOnOff: on
    # 官方建议：确保同一组中的每个消费者订阅相同的主题。
    groupName: mygroup
    # 服务地址
    namesrvAddr: 129.211.71.185:9876
    # 接收该 Topic 下所有 Tag
    topics: mytopic~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
# 配置 Group  Topic  Tag
rocket:
  #发送消息group不用填写
  group: mygroup
  topic: mytopic
  tag: rocketTag

eureka:
  client:
    serviceUrl:
      defaultZone: http://134.175.217.13:8761/eureka/

  # Redis服务器地址
redis:
  host: 134.175.217.13
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password: password
  timeout: 30000
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 30
  # 连接池中的最大空闲连接
  maxIdle: 10
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 1800000
  softMinEvictableIdleTimeMillis: 10000
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  maxWaitMillis: 1500
  testOnBorrow: true
  testWhileIdle: true
  blockWhenExhausted: false
  JmxEnabled: false
